### ISSUE TITLE
Android setup guide should be checked for being up to date

### ISSUE THREAD

**Issue by pizthewiz** [openframeworks/ofSite#315]
A [forum user mentioned](http://forum.openframeworks.cc/t/your-android-setup-tutorial-is-broken-and-you-should-remove-it) some difficulties with the [Android ADT setup guide](http://openframeworks.cc/setup/android-eclipse/) and while lean of any details, it might be worth a quick look to see if the specifics are still relevant and accurate. While there is an effort to bring up [Android Studio support](https://github.com/openframeworks/openFrameworks/issues/3408), it isn't clear that it will be integrated into OF-0.9.0, so the existing setup guide may need to live on a while longer.

**Comment by joaodafonseca** [comment]
hi guys, any update on this? also follow the tutorial and it's not working for me. Got the following errors when trying to build an example.
![screen shot 2015-02-23 at 13 32 47 1](https://cloud.githubusercontent.com/assets/1932216/6327809/9cd07e26-bb60-11e4-80f3-062be355a513.png)

thanks in advance.

**Comment by mruegenberg** [comment]
Since I found the [current guide](https://github.com/openframeworks/openFrameworks/blob/master/docs/android.md) to contain some unnecessary steps, with some things missing, here is what I did to get the empty example to work in Android Studio 1.4 preview (version 1.3 should be the same):
(These instructions will become outdated if and when oF is updated to use the new NDK integration.)

1. Download and unpack the Android version of oF 0.9.0 RC1 [here](http://forum.openframeworks.cc/t/0-9-0-release-candidate-1/20434)
2.  Create a file `/libs/openFrameworksCompiled/project/android/gradle.properties` containing the text `android.useDeprecatedNdk=true`.
3. File > New > Import Project. Go to of_v0.9.0RC1_android_release/libs/openFrameworksCompiled/project/android/ and select settings.gradle
4. Click `Ok` when prompted for fixes
5. Click on the green arrow at the top (it will take a while the first time). 
   If you have a device plugged in or an emulator running, the empty example should build and run. (It only worked in a device for me!)

### To add other examples or your own projects:
Confusingly, the examples directory is shown in the Project panel in Android Studio. To add another example, you need to copy `build.gradle` from the empty example to its directory. 
You also need to explicitly add it to `settings.gradle`, e.g `include 'examples:android:androidAdvanced3DExample'`. Right now, the only way I've found to update the project correctly is to repeat the *Import Project* step above. Before doing that, you need to delete all `.iml` files and the `project/android/.idea` directory.
(Some examples don't work even with this process.)

For multiple projects to work, you need a current Gradle version: change *com.android.tools.build:gradle:* in `build.gradle (Project: android)` to be whatever Android Studio's fix-it suggests (e.g *1.3.0*).

See also https://github.com/openframeworks/openFrameworks/issues/4168

**Comment by joaodafonseca** [comment]
Hi @mruegenberg 
I followed your steps but when running the example I got the following error

![screen shot 2015-09-10 at 17 40 47](https://cloud.githubusercontent.com/assets/1932216/9792953/3e90fa64-57e3-11e5-8d10-eef1fd063195.png)


Any ideas of what could be wrong?

**Comment by mruegenberg** [comment]
Hmm, that's weird, since you obviously have the right package for an Android project. 
You could try whether the space in your path is a problem. Other than that, I don't really know, but if you post your whole compile log, that it would be easier to see what's going on.

**Comment by joaodafonseca** [comment]
Hi @mruegenberg thanks for your answer, restarting my computer did the trick. Still not sure what was the problem, but now it works, running openframeworks in android studio like a charm :)

**Comment by edap** [comment]
Following the [current guide](https://github.com/openframeworks/openFrameworks/blob/master/docs/android.md) but using the last version of the ndk (r10d) as suggested in the [forum](http://forum.openframeworks.cc/t/android-studio-always-recompiling-openframeworks/20752), and creating  a file /libs/openFrameworksCompiled/project/android/gradle.properties containing the text `android.useDeprecatedNdk=true` as suggested by @mruegenberg, I was finally able to start the emulator. 
But the application crash with this error message:
```bash
1:46.706    2091-2091/? I/OF﹕ static init
09-17 23:58:46.707    2091-2091/? I/OF﹕ failed neon detection, loading not-neon library
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cc.openframeworks.androidEmptyExample-1/base.apk"],nativeLibraryDirectories=[/data/app/cc.openframeworks.androidEmptyExample-1/lib/x86, /data/app/cc.openframeworks.androidEmptyExample-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libneondetection.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:367)
            at java.lang.System.loadLibrary(System.java:1076)
            at cc.openframeworks.OFAndroid.<clinit>(OFAndroid.java:1028)
            at cc.openframeworks.androidEmptyExample.OFActivity.onCreate(OFActivity.java:18)
            at android.app.Activity.performCreate(Activity.java:6237)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-17 23:58:46.707    2091-2091/? D/AndroidRuntime﹕ Shutting down VM
09-17 23:58:46.707    2091-2091/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: cc.openframeworks.androidEmptyExample, PID: 2091
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cc.openframeworks.androidEmptyExample-1/base.apk"],nativeLibraryDirectories=[/data/app/cc.openframeworks.androidEmptyExample-1/lib/x86, /data/app/cc.openframeworks.androidEmptyExample-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libOFAndroidApp.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:367)
            at java.lang.System.loadLibrary(System.java:1076)
            at cc.openframeworks.OFAndroid.<clinit>(OFAndroid.java:1038)
            at cc.openframeworks.androidEmptyExample.OFActivity.onCreate(OFActivity.java:18)
            at android.app.Activity.performCreate(Activity.java:6237)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
I'm emulating a nexus 5 API 23 x86, I'm on MacOS, using Android Studio 1.3.2, and the latest nightly android release (17 september)

**Comment by arturoc** [comment]
you need to compile in release mode or add:

```
ABIS_TO_COMPILE_DEBUG = x86 
```

in the config.make in your project. the emulator is using x86 cpu instead of arm7 which is what the debug target defaults to. when you try to run it, it can't find the library.

we could enable both arm7 and x86 with:


```
ABIS_TO_COMPILE_DEBUG = x86 armv7
```

and then it would work in both the emulator and most devices but it would take a lot to compile

**Comment by edap** [comment]
hello @arturoc . There is no `config.make` file in the folder `of_v20150917_android_release/libs/openFrameworksCompiled/project/android`.
I've created one adding  `ABIS_TO_COMPILE_DEBUG = x86` and this time the project builds.
The problem is that the emulator does not show any OF application, just an android desktop.
I will try with a real device later.

Should I open a PR with the updates at the wiki, and at the `gradle.properties` file?

**Comment by arturoc** [comment]
no, config.make is in the examples not in the openFrameworks project folder. there's already a PR for the changes to the readme so if you want to send one for the gradle.properties?

**Comment by edap** [comment]
sure! https://github.com/openframeworks/openFrameworks/pull/4377

the guide talks androidEmpty Example https://github.com/openframeworks/openFrameworks/blob/master/docs/android.md#build-and-run , that is located  `libs/openFrameworksCompiled/project/android`

**Comment by edap** [comment]
i think this issue can be close
