### ISSUE TITLE
Change log not found

### ISSUE THREAD

**Issue by borg** [openframeworks/ofSite#354]
Change log not found
http://openframeworks.cc/0.9.0/download/
https://raw.githubusercontent.com/openframeworks/openFrameworks/0.9.0RC2/CHANGELOG.md

**Comment by javl** [comment]
@borg:
Where did you find those links? I can only find them in [this forum post](http://forum.openframeworks.cc/t/0-9-0-documentation/21268), but the links with /0.9.0/ in them don't seem to work anymore (point to the main page). On the site itself, I can't find any link with the version number in it. Maybe this was only used before 0.9 was released and the problem was fixed when it became the current version? 

Changelog link on [http://openframeworks.cc/download/](http://openframeworks.cc/download/) seems to work.

**Comment by arturoc** [comment]
this was before we did the final release, the web for the RC still didn't have the changelog ready but it's fixed now, thanks!
